services:
  - type: web
    name: mychat
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn mychat.wsgi:application"
    environment:
      pythonVersion: 3.12.3
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mychat-db
          property: connectionString
      - key: DEBUG
        value: "False"

databases:
  - name: mychat-db
  