# Generated by Django 5.1.6 on 2025-06-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roommemeber",
            old_name="room_name",
            new_name="name",
        ),
    ]
