# Generated by Django 5.1.6 on 2025-06-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_room_name_roommemeber_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommemeber",
            name="room_name",
            field=models.CharField(default="hello", max_length=100),
            preserve_default=False,
        ),
    ]
