# Generated by Django 5.1.6 on 2025-06-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_room_alter_roommemeber_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.roommemeber",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="total_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
